package model.persistence;

import model.BossLog;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.Stream;

// Represents a reader object that parses the JSON file generated by JsonWriter to restore the state of a BossLog
// object
// Source code largely based on provided example in Phase 2 instructions
// (https://github.students.cs.ubc.ca/CPSC210/JsonSerializationDemo.git)
public class JsonReader {
    private final String src;

    // EFFECTS: constructs reader to read from source file
    public JsonReader(String source) {
        this.src = source;
    }

    // EFFECTS: reads BossLog from file and returns it;
    // throws IOException if an error occurs reading data from file
    public BossLog read() throws IOException {
        String jsonData = readFile(this.src);
        JSONObject jsonObject = new JSONObject(jsonData);
        BossLog log = new BossLog();
        addEntries(log, jsonObject);
        return log;
    }

    // MODIFIES: log
    // EFFECTS: Parse each entry in the json object and generate log entries sequentially
    private void addEntries(BossLog log, JSONObject jsonObject) {
        JSONArray kills = (JSONArray) jsonObject.get("kills");
        for (Object k : kills) {
            JSONObject entryAsJson = (JSONObject) k;
            try {
                String bossName = entryAsJson.getString("killed");
                log.addNewEntryByName(bossName, entryAsJson.getInt("time"), entryAsJson.getInt("value"));
            } catch (JSONException e) {
                // No entries, return without doing anything
                return;
            }
        }
    }

    // EFFECTS: reads source file as string and returns it
    private String readFile(String source) throws IOException {
        StringBuilder contentBuilder = new StringBuilder();

        try (Stream<String> stream = Files.lines(Paths.get(source), StandardCharsets.UTF_8)) {
            stream.forEach(s -> contentBuilder.append(s));
        }

        return contentBuilder.toString();
    }
}
