package model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Stack;

public class BossLog {
    ArrayList<Boss> bosses;
    ArrayList<KillEntry> kills;  // store all the entries generated by BossLog
    private static Boss vorkath = new Boss("Vorkath");
    private static Boss giantMole = new Boss("Giant Mole");
    private static Boss zulrah = new Boss("Zulrah");

    // EFFECTS: initialize the application with Bosses
    public BossLog() {
        this.bosses = new ArrayList<>();
        this.kills = new ArrayList<>();
        this.bosses.add(vorkath);
        this.bosses.add(giantMole);
        this.bosses.add(zulrah);
    }

//    public void addNewEntry(int bossIdx, int time, Item[] drops) {
//        Boss boss = this.bosses.get(bossIdx);
//        KillEntry newEntry = new KillEntry(time, drops);
//        boss.add(newEntry);
//        this.kills.add(newEntry);
//    }

    public void addNewEntry(int bossIdx, int time, int value) {
        Boss boss = this.bosses.get(bossIdx);
        KillEntry newEntry = new KillEntry(boss, time, value);
        boss.add(newEntry);
        this.kills.add(newEntry);
    }

    public Boss[] getBosses() {
        return this.bosses.toArray(new Boss[0]);
    }

    public KillEntry getEntry(int x) {
        return this.kills.get(x);
    }

    public KillEntry getMostRecent(int x) {
        return this.kills.get(this.kills.size() - 1 - x);
    }

    // EFFECTS: Returns the total number of logged kills
    public int getTotalKills() {
        return this.kills.size();
    }
}
